# Generated by Django 4.2 on 2023-06-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=155, verbose_name='Название мероприятия')),
                ('foto_event', models.ImageField(upload_to='event/', verbose_name='Фотография ивента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title_event', models.CharField(max_length=255, verbose_name='Заголовок мероприятия')),
                ('event_desc', models.TextField(max_length=255, verbose_name='Описасние мероприятия')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
