# Generated by Django 4.2 on 2023-06-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='buy_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buy_courses', to='courses.courses'),
            preserve_default=False,
        ),
    ]
