# Generated by Django 4.2 on 2023-06-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
