# Generated by Django 4.2 on 2023-06-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_buy_buy_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='desc_course',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='foto_course',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='name_course',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='less',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='students',
        ),
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.CharField(default=1, max_length=100, verbose_name='Длительность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_courses', to='courses.category', verbose_name='Категория'),
        ),
    ]
