# Generated by Django 4.2 on 2023-06-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_category_rename_desc_course_courses_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(verbose_name='Описание продукта'),
        ),
    ]
