# Generated by Django 4.2 on 2023-06-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='url',
            field=models.URLField(default=1, verbose_name='Ссылка на курс'),
            preserve_default=False,
        ),
    ]
