# Generated by Django 4.2 on 2023-06-13 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_alter_courses_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='buy_course',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='email',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='phone',
        ),
        migrations.AddField(
            model_name='buy',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buys_courses', to='courses.courses', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='buy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата покупки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users_buys', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
