# Generated by Django 4.2 on 2023-06-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Бонусный код'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=1, max_length=10, verbose_name='Реферальный код'),
            preserve_default=False,
        ),
    ]
