# Generated by Django 4.2 on 2023-06-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(default=1, max_length=20, verbose_name='ID счета'),
            preserve_default=False,
        ),
    ]
