# Generated by Django 4.1.5 on 2023-06-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bonus_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(max_length=20, verbose_name='Реферальный код'),
        ),
    ]
