# Generated by Django 4.2 on 2023-06-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='profile_images/', verbose_name='Фотография'),
            preserve_default=False,
        ),
    ]
