# Generated by Django 4.2 on 2023-06-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_1', models.ImageField(upload_to='about_slide/', verbose_name='Фото')),
                ('info', models.CharField(max_length=255, verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконки')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('message', models.TextField(max_length=255, verbose_name='Введите ваше сообщение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=155, verbose_name='Название мероприятия')),
                ('foto_event', models.ImageField(upload_to='event/', verbose_name='Фотография ивента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title_event', models.CharField(max_length=255, verbose_name='Заголовок мероприятия')),
                ('event_desc', models.TextField(max_length=255, verbose_name='Описасние мероприятия')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_site', models.CharField(max_length=150, verbose_name='Название колледжа')),
                ('logo_site', models.ImageField(upload_to='logo/', verbose_name='Логотип колледжа')),
                ('info_site', models.CharField(max_length=255, verbose_name='Дополнительная информация о колледже')),
            ],
            options={
                'verbose_name': 'Настройки колледжа',
                'verbose_name_plural': 'Настройки колледжа',
            },
        ),
    ]
