# Generated by Django 4.2 on 2023-06-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='setting',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='setting',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='setting',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон номер'),
        ),
        migrations.AddField(
            model_name='setting',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube'),
        ),
    ]
