# Generated by Django 4.2 on 2023-06-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_setting_email_setting_facebook_setting_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='info',
        ),
        migrations.RemoveField(
            model_name='about',
            name='slide_1',
        ),
        migrations.AddField(
            model_name='about',
            name='descriptions',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=1, upload_to='about_slide/', verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='titile',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
