# Generated by Django 4.2 on 2023-06-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_about_info_remove_about_slide_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='titile',
            new_name='title',
        ),
    ]
