# Generated by Django 4.2 on 2023-06-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_rename_descriptions_about_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_course', models.CharField(max_length=255, verbose_name='Онлайн курсов')),
                ('active_students', models.CharField(max_length=255, verbose_name='Активных студентов')),
                ('expert_instructor', models.CharField(max_length=255, verbose_name='Экспертных инструкторов')),
                ('hours_educate', models.CharField(max_length=255, verbose_name='Часов обучения')),
            ],
            options={
                'verbose_name': 'Мы в числах',
                'verbose_name_plural': 'Мы в числах',
            },
        ),
    ]
