# Generated by Django 4.2 on 2023-06-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonym_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=155, verbose_name='кому')),
                ('message2', models.TextField(max_length=255, verbose_name='Введите ваше сообщение')),
            ],
            options={
                'verbose_name': 'Анонимное сообщение',
                'verbose_name_plural': 'Анонимные сообщения',
            },
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Настройка сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AlterField(
            model_name='setting',
            name='info_site',
            field=models.CharField(max_length=255, verbose_name='Дополнительная информация о сайте'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo_site',
            field=models.ImageField(upload_to='logo/', verbose_name='Логотип сайта'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name_site',
            field=models.CharField(max_length=150, verbose_name='Название сайта'),
        ),
    ]
