# Generated by Django 4.2 on 2023-06-21 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_teacher', models.ImageField(upload_to='foto_teacher/', verbose_name='фотография преподователя')),
                ('name_teacher', models.CharField(max_length=155, verbose_name='ФИО преподователя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта учителя')),
                ('number', models.CharField(max_length=155, verbose_name='Номер телефона')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.courses')),
            ],
            options={
                'verbose_name': 'Преподователь',
                'verbose_name_plural': 'Преподователи',
            },
        ),
    ]
