# Generated by Django 4.2 on 2023-06-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Фейсбук пользователя'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Инстаграм пользователя'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Линкедин пользователя'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Ютуб пользователя'),
        ),
    ]
