# Generated by Django 4.2 on 2023-06-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teachers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='number',
            field=models.CharField(default=1, max_length=155, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
